on:
  push:
    branches: [ main ]
jobs:
  build-push-gar:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: sretest
      PROJECT_ID: glassy-outcome-415920
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: gcloud auth configure-docker us-south1-docker.pkg.dev --quiet

      - name: Push Docker Image to Artifact Registry
        run: |
          docker tag $IMAGE_NAME:latest us-south1-docker.pkg.dev/$PROJECT_ID/lab1mod2/$IMAGE_NAME:latest
          docker push us-south1-docker.pkg.dev/$PROJECT_ID/lab1mod2/$IMAGE_NAME:latest

      - uses: simenandre/setup-gke-gcloud-auth-plugin@v1
        name: Setup GKE gcloud Auth Plugin

      - uses: google-github-actions/get-gke-credentials@v1
        name: Get GKE credentials
        with:
          cluster_name: lab-mod2
          location: us-south1
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Deploy to GKE
        run: |
          kubectl apply -f resources.yaml

###