on:
  push:
    branches: [ main ]
jobs:
  build-push-gar:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: sretest
      PROJECT_ID: ambient-mystery-415617
    steps:
    - uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .


    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker us-south1-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      run: |-
        docker tag $IMAGE_NAME:latest us-south1-docker.pkg.dev/$PROJECT_ID/lab1mod2/$IMAGE_NAME:latest
        docker push us-south1-docker.pkg.dev/$PROJECT_ID/lab1mod2/$IMAGE_NAME:latest

    - name: deploy to gke
      run: |
        sudo apt-get update && sudo apt-get --only-upgrade install google-cloud-sdk-log-streaming google-cloud-sdk-enterprise-certificate-proxy google-cloud-sdk-kubectl-oidc google-cloud-sdk-nomos google-cloud-sdk-cbt google-cloud-cli-docker-credential-gcr google-cloud-sdk-kpt google-cloud-sdk-minikube google-cloud-sdk-spanner-migration-tool google-cloud-sdk-pubsub-emulator google-cloud-sdk-cloud-build-local google-cloud-sdk-anthos-auth google-cloud-sdk-app-engine-python-extras google-cloud-sdk-app-engine-go google-cloud-sdk-local-extract google-cloud-sdk-app-engine-python google-cloud-sdk-skaffold google-cloud-sdk-spanner-emulator kubectl google-cloud-sdk-app-engine-grpc google-cloud-sdk-bigtable-emulator google-cloud-sdk-cloud-run-proxy google-cloud-sdk-istioctl google-cloud-sdk-terraform-tools google-cloud-sdk-app-engine-java google-cloud-sdk-harbourbridge google-cloud-sdk-package-go-module google-cloud-sdk-gke-gcloud-auth-plugin google-cloud-sdk-config-connector google-cloud-sdk google-cloud-sdk-firestore-emulator google-cloud-sdk-datastore-emulator
        gcloud container clusters get-credentials lab-mod2 --region us-south1
        kubectl apply -f resources.yaml

##